# 算法相关
seed: null
reward_shaping: False
reward_mimic: True
reward_success: 200
reward_defeat: -200
reward_scale: 3.0
#state_last_action: True # False: critic adds last action internally
#state_timestep_number: False
episode_limit: 100
obs_timestep_number: False
debug: False

# 任务相关
joint_pos_size: 7
joint_vel_size: 7
eef_pos_size: 3
eef_quat_size: 4
ft_size: 6
peg_pos_size: 3
peg_to_hole_size: 3
robot_state_size: 38
object_state_size: 19
n_agents: 2
n_actions: 7
obs_choose: "all"
trajectory_data_path: "data/trajectory.csv"
ms_xl: -0.25
ms_xh: 0.25
ms_yl: -0.3
ms_yh: 0.3
ms_zl: 0
ms_zh: 1.5

# Mujoco 相关
has_renderer: False
has_offscreen_renderer: False
ignore_done: False
use_camera_obs: False
control_freq: 20
camera_name: "frontview"
camera_heights: 512
camera_widths: 512


