offpg_args:
  evaluate: True
  checkpoint_path: "results/models/offpg_dualarm__2022-11-03_15-45-58"
  runner: "episode"
  batch_size_run: 1

evaluate_args:
  evaluate_n_episodes: 10
  video_record: True
  skip_frame: 1
  video_save_path: "video"
  path_record: False
  path_save_path: "path"
  ft_record: False
  ft_save_path: "ft"
  state_record: False
  state_save_path: "state"

env_args:
  # Mujoco 相关
#  has_renderer: True
  has_offscreen_renderer: True
  camera_name: "sideview"
  use_camera_obs: True
  camera_heights: 1024
  camera_widths: 1024