evaluate: True
# checkpoint_path: "/home/fyw/Documents/projects/dual-arm-mimic/results/models/offpg_smac__2021-03-08_22-00-27"
# checkpoint_path: "/home/fyw/Documents/projects/dual-arm-mimic/results/models/offpg_smac__2021-03-11_20-46-43"
# checkpoint_path: "/home/fyw/Documents/projects/dual-arm-mimic/results/models/offpg_smac__2021-03-20_10-13-41"
# checkpoint_path: "/home/fyw/Documents/projects/dual-arm-mimic/results/models/offpg_smac__2021-03-23_21-25-52"
# checkpoint_path: "/home/fyw/Documents/projects/dual-arm-mimic/results/models/offpg_smac__2021-03-29_12-51-25"
# checkpoint_path: "/home/fyw/Documents/projects/dual-arm-mimic/results/models/offpg_smac__2021-04-01_17-44-01"
# checkpoint_path: "/home/fyw/Documents/projects/dual-arm-mimic/results/models/offpg_smac__2021-04-01_17-47-36"
# checkpoint_path: "/home/fyw/Documents/projects/dual-arm-mimic/results/models/offpg_smac__2021-04-01_22-48-38"
# checkpoint_path: "/home/fyw/Documents/projects/dual-arm-mimic/results/models/offpg_smac__2021-04-01_23-16-26"

checkpoint_path: "/home/fyw/Documents/projects/dual-arm-mimic/results/models/offpg_smac__2022-02-12_19-16-17"

runner: "episode"
batch_size_run: 1 #10
video_record: False
skip_frame: 1
path_record: True
ft_record: False
state_record: True

env_args:
  reward_shaping: True
  reward_success: 200
  reward_defeat: -200
  reward_scale: 3.0
  replay_dir: ""
  replay_prefix: ""
  state_last_action: True
  state_timestep_number: False
  seed: null
  debug: False
  episode_limit: 100
  has_renderer: True
  # has_renderer: False
  # has_offscreen_renderer: True
  # camera_name: "frontview"
  # use_camera_obs: True
  # camera_heights: 1024
  # camera_widths: 1024